web:
    image: nginx:latest
    ports:
        - "8080:8080"
        - "443:443"
    volumes:
        - ./:/code
        - ./site.conf:/etc/nginx/conf.d/site.conf
        - ./www.ushinef.com.crt:/etc/nginx/ssl/www.ushinef.com.crt
        - ./www.ushinef.com.key:/etc/nginx/ssl/www.ushinef.com.key
    links:
        - php
    privileged: true

php:
    image: registry.cn-hangzhou.aliyuncs.com/haoji/ushinef_php:1.2
    volumes:
        - ./:/code
        - ./php.ini:/usr/local/etc/php/php.ini
    privileged: true
    links:
        - redis
        - mysql

redis:
    image: redis:latest
    ports:
        - "6379:6379"
    # environment:
    #     - REDIS_PASS=verysecret

mysql:
    image: mysql:8.0.12
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0 --default_authentication_plugin=mysql_native_password
    ports:
        - "3306:3306"
    environment:
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=verysecret
        - MYSQL_ROOT_PASSWORD=verysecret
        - MYSQL_DATABASE=yuming
    volumes:
        - ./data/mysql:/var/lib/mysql
        - ./:/code


